---
- hosts: debian12
  become: true
  tasks:
    - name: Instala dependencias y Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Añade clave GPG oficial de Docker
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Añade el repositorio de Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
        state: present

    - name: Instala docker-ce
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Asegura que Docker está activo
      service:
        name: docker
        state: started
        enabled: true

    - name: Lanza nginx con Docker
      docker_container:
        name: nginx
        image: nginx:latest
        state: started
        ports:
          - "80:80"
          - "443:443"
        restart_policy: unless-stopped

    - name: Lanza MySQL con Docker
      docker_container:
        name: mysql
        image: mysql:8.0
        state: started
        ports:
          - "3306:3306"
        volumes:
          - mysql_data:/var/lib/mysql
        restart_policy: unless-stopped
        env:
          MYSQL_ROOT_PASSWORD: "manager"

    - name: Esperar hasta que MySQL esté listo para conexiones (máx 60s)
      ansible.builtin.shell: sleep 60
          
    - name: Crea usuario en MySQL usando shell
      ansible.builtin.shell: |
        docker exec -i mysql mysql -u root -p'manager' -e "
            CREATE USER IF NOT EXISTS 'david'@'%' IDENTIFIED WITH mysql_native_password BY '1234'; 
            GRANT ALL PRIVILEGES ON *.* TO 'david'@'%'; 
            FLUSH PRIVILEGES;
        "
        
    - name: Lanza PostgreSQL con Docker
      docker_container:
        name: postgres
        image: postgres:16
        state: started
        ports:
          - "5432:5432"
        volumes:
          - pg_data:/var/lib/postgresql/data
        restart_policy: unless-stopped
        env:
          POSTGRES_PASSWORD: "manager"
          POSTGRES_USER: "postgres"

    - name: Esperar hasta que PostgreSQL esté listo para conexiones (máx 60s)
      ansible.builtin.shell: sleep 60

    - name: Crea usuario en PostgreSQL usando shell
      ansible.builtin.shell: |
        docker exec -i postgres psql -U postgres -c "DO
        \$\$
        BEGIN
          IF NOT EXISTS (SELECT FROM pg_catalog.pg_user WHERE usename = 'david') THEN
            CREATE USER david WITH PASSWORD '1234' CREATEDB;
          ELSE
            ALTER USER david WITH CREATEDB;
          END IF;
        END
        \$\$;"

