services:
  lastfm_db:
    image: postgres:15-alpine
    container_name: lastfm_postgres
    restart: always
    environment:
      POSTGRES_USER: lastfm_user
      POSTGRES_PASSWORD: lastfm_password123
      POSTGRES_DB: lastfm_data
    ports:
      - "5432:5432"
    volumes:
      - lastfm_pgdata:/var/lib/postgresql/data

  lastfm_api:
    image: python:3.11-slim
    container_name: lastfm_fastapi
    restart: always
    working_dir: /app
    # El contenedor instalará las librerías y arrancará Uvicorn automáticamente
    command: bash -c "pip install fastapi uvicorn psycopg2-binary && uvicorn backend.api:app --host 0.0.0.0 --port 8000"
    environment:
      - DB_HOST=lastfm_postgres  # <-- Clave para que hable con el contenedor de la BD
    ports:
      - "8000:8000"
    volumes:
      - ../:/app   # Monta todo tu repositorio dentro del contenedor
    depends_on:
      - lastfm_db

volumes:
  lastfm_pgdata:
